version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: rdbc_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwordfile:/mosquitto/config/passwordfile
      - ./mosquitto/mosquitto-server.crt:/mosquitto/config/mosquitto-server.crt
      - ./mosquitto/mosquitto-server.key:/mosquitto/config/mosquitto-server.key
      - ./mosquitto/ca.crt:/mosquitto/config/ca.crt
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - mynetwork

  backend:
    build: ./server
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/usr/src/app
      - ./mosquitto/ca.crt:/usr/src/app/ca.crt
      - ./certs/client.crt:/usr/src/app/client.crt
      - ./certs/client.key:/usr/src/app/client.key

    depends_on:
      - mongodb
      - mosquitto
    environment:
      - USERNAME=admin
      - PASSWORD=admin123
      - MQTT_BROKER_URL=mqtts://mosquitto:8883
      - MQTT_CA_CERT_PATH=/usr/src/app/ca.crt
      - MQTT_CLIENT_CERT_PATH=/usr/src/app/client.crt
      - MQTT_CLIENT_KEY_PATH=/usr/src/app/client.key
      - MQTT_USERNAME=tester
      - MQTT_PASSWORD=1234
    networks:
      - mynetwork

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - frontend-data:/usr/src/app
      - /usr/src/app/node_modules
      - ./certs/localhost.pem:/usr/src/app/localhost.pem
      - ./certs/localhost-key.pem:/usr/src/app/localhost-key.pem
    environment:
      - SSL_KEY_PATH=/usr/src/app/localhost-key.pem
      - SSL_CERT_PATH=/usr/src/app/localhost.pem
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  mosquitto-data:
    driver: local
  mosquitto-log:
    driver: local
  backend-data:
    driver: local
  frontend-data:
    driver: local
